### ISSUE TITLE
submissionStream

### ISSUE THREAD

**Issue by ghost** [RedditBotting/BLBForChomskydoz#2]
This one's a friendly suggestion rather than a pull request. As you can see, I'm pretty opinionated about all this, so feel free to ignore any or all of my suggestions.

Anyway, I used to have all my reddit bots running in an infinite loop 24/7, but over time I found it just added too much maintenance hassle. Even when you think you are (or even really are) addressing every possible exception, you'll still have crashes occasionally, and if you're not checking up on the bot, it could be going a while not running without you realizing it.

So I've migrated to a model where all my bots are written to execute once and then close, and then I put them on a cron job that runs every two minutes. This means that posters will have to wait up to two minutes for a response, but I consider that pretty reasonable. This also means that even if the bot crashes on a particular run, it's guaranteed to run again two minutes later, so you don't have a situation where the bot crashes and you're not in a position to restart it for hours and hours.

**Comment by RedditBotting** [comment]
I agree, that would definitely be ideal. Having it always running would be pretty unnecessary, and if we've got it just scheduled to run that will make adjusting any config files (e.g. adding Chomskydoz quotes?) since we'll have time to make changes while the script isn't accessing them.

It looks like in your SLS bot you're pulling in the most recent 5 threads and then checking the comments to make sure you haven't already commented it, is that the solution you've been using for all your bots? It seems like that would work well for BL as well since it doesn't seem to have so many submissions that we would miss any.

**Comment by ghost** [comment]
It depends on the needs of the subreddit and what exactly the bot is responding to. On SLS I can be pretty much 100% sure that we're not going to get more than 5 submissions in two minutes, so it seems like a safe enough number (and one that I can easily increase if the need ever arises).

There are a few different ways to prevent a bot from posting twice. The SLSbot's solution works well enough, because when you pull a reddit submission from the API, you automatically get all the top-level comments along with it, so checking their authors doesn't involve any further API calls. A lot of people keep databases of the post IDs they've responded to, but I've always considered that a touch unwieldy. My FULLCOMMUNISM bot responds to messages and mentions, so it simply marks them as read when it's done with them, but obviously that doesn't apply here.

**Comment by RedditBotting** [comment]
Yeah I saw one or two bots when I was looking in to praw that were storing all the IDs in SQL databases or other things, agreed that would be unnecessary though. I'm gonna go ahead and change the bot to use the same kind of implementation as your SLS bot instead of using the continuous stream. As long as BL doesn't somehow become a default sub (ha) that should be sufficient.
